name: Lesson 3

on:
  push:
    branches:
      - lesson-3
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
#      - run: npm install && npm run build (commented out to save learner time)
      - name: Generate deployment package
        run: zip -r deploy.zip build Dockerfile
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk'
        run: echo Placeholder for Deployment
  functional_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
        steps:
          - uses: actions/checkout@v4
          - run: npm install
          - run: npm test
    needs: [functional_test]